### ISSUE TITLE
Change repo name to something useful

### ISSUE THREAD

**Issue by sascha1337** [CosmosContracts/juno-ts#1]
having a repo called 'typescript' is not beneficial, the KPI // conversion rate of this alpha repo being found and used is inadequate of its quality content inside.

**Comment by pyramation** [comment]
goodpoint, I didn't want to confuse people by calling it juno or juno-network, as that name should be reserved for the SDK. I'm curious if folks have suggestions as how to not confuse devs.

**Comment by pyramation** [comment]
what do you think of juno-ts?

**Comment by reecepbcups** [comment]
@pyramation I am good with juno-ts

**Comment by pyramation** [comment]
renamed!
