### ISSUE TITLE
getting balance from `JunoSwapClient`

### ISSUE THREAD

**Issue by aidanaden** [CosmosContracts/juno-ts#4]
In the code example below, I'm attempting to fetch the balance of the account `juno1qff5wml0r3r7zm6tgv4k9wqnvelx8j7jss6a7g` using the `juno/atom` contract pair address, where `_signer` is a keplr `OfflineSigner`.

The balance logged is always "0", even though there is `0.136256` juno in the account. Am I using the `JunoSwapClient.balance` function wrongly? Any help is welcome. Thanks!

```
const signingCosmWasmClient = await SigningCosmWasmClient.connectWithSigner(
  "https://rpc-juno.itastakers.com",
  _signer,
  {
    gasPrice: {
    amount: Decimal.zero(3),
    denom: "ujuno",
  },
});

const swapClient = new JunoSwapClient(
  signingCosmWasmClient,
  "juno1qff5wml0r3r7zm6tgv4k9wqnvelx8j7jss6a7g",
  "juno1sg6chmktuhyj4lsrxrrdflem7gsnk4ejv6zkcc4d3vcqulzp55wsf4l4gl"
);

const { balance } = await swapClient.balance({
  address: juno1qff5wml0r3r7zm6tgv4k9wqnvelx8j7jss6a7g,
});

console.log({ balance });
```

**Comment by pyramation** [comment]
I've made an example from your snippet and can verify it returns 0.

https://github.com/pyramation/swap-test/blob/71bc74991dc6faa0b61df8fa9b05b4f30301f263/pages/index.tsx#L103-L115

How can we check this on mintscan?

cc @ben2x4

**Comment by pyramation** [comment]
looks relevant https://github.com/Wasmswap/wasmswap-contracts/issues/73

**Comment by JakeHartnell** [comment]
RIP JunoSwap. lol

Wynd and the others are the future.
